export const firstColumnImages = [
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 1.5, match3Payout: 2.4 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 1.6, match3Payout: 2.5 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 1.7, match3Payout: 2.6 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 1.8, match3Payout: 2.7 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 1.9, match3Payout: 2.8 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 2.0, match3Payout: 2.9 },
  { id: "p7", src: process.env.PUBLIC_URL + "/puppypics/7.jpg", match2Payout: 2.1, match3Payout: 3.0 },
  { id: "p8", src: process.env.PUBLIC_URL + "/puppypics/8.jpg", match2Payout: 2.2, match3Payout: 3.1 },
  { id: "p9", src: process.env.PUBLIC_URL + "/puppypics/9.jpg", match2Payout: 2.3, match3Payout: 3.2 },
  { id: "p10", src: process.env.PUBLIC_URL + "/puppypics/10.jpg", match2Payout: 0.0, match3Payout: 30.0 },
  { id: "p11", src: process.env.PUBLIC_URL + "/puppypics/11.jpg", match2Payout: 0.0, match3Payout: 0.0 },
];
export const secondColumnImages = [
  { id: "p9", src: process.env.PUBLIC_URL + "/puppypics/9.jpg", match2Payout: 2.3, match3Payout: 3.2 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 1.5, match3Payout: 2.4 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 1.8, match3Payout: 2.7 },
  { id: "p8", src: process.env.PUBLIC_URL + "/puppypics/8.jpg", match2Payout: 2.2, match3Payout: 3.1 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 1.9, match3Payout: 2.8 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 1.6, match3Payout: 2.5 },
  { id: "p7", src: process.env.PUBLIC_URL + "/puppypics/7.jpg", match2Payout: 2.1, match3Payout: 3.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 2.0, match3Payout: 2.9 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 1.7, match3Payout: 2.6 },
];
export const thirdColumnImages = [
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 1.7, match3Payout: 2.6 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 2.0, match3Payout: 2.9 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 1.6, match3Payout: 2.5 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 1.8, match3Payout: 2.7 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 1.9, match3Payout: 2.8 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 1.5, match3Payout: 2.4 },
  { id: "p7", src: process.env.PUBLIC_URL + "/puppypics/7.jpg", match2Payout: 2.1, match3Payout: 3.0 },
  { id: "p9", src: process.env.PUBLIC_URL + "/puppypics/9.jpg", match2Payout: 2.3, match3Payout: 3.2 },
  { id: "p8", src: process.env.PUBLIC_URL + "/puppypics/8.jpg", match2Payout: 2.2, match3Payout: 3.1 },
];

export const allImageObjects = [
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },
  { id: "p1", src: process.env.PUBLIC_URL + "/puppypics/1.jpg", match2Payout: 3.0, match3Payout: 5.0 },


  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },
  { id: "p2", src: process.env.PUBLIC_URL + "/puppypics/2.jpg", match2Payout: 4.0, match3Payout: 6.0 },


  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },
  { id: "p3", src: process.env.PUBLIC_URL + "/puppypics/3.jpg", match2Payout: 5.0, match3Payout: 7.0 },


  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },
  { id: "p4", src: process.env.PUBLIC_URL + "/puppypics/4.jpg", match2Payout: 6.0, match3Payout: 8.0 },


  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },
  { id: "p5", src: process.env.PUBLIC_URL + "/puppypics/5.jpg", match2Payout: 7.0, match3Payout: 9.0 },


  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },
  { id: "p6", src: process.env.PUBLIC_URL + "/puppypics/6.jpg", match2Payout: 8.0, match3Payout: 10.0 },


  { id: "p7", src: process.env.PUBLIC_URL + "/puppypics/7.jpg", match2Payout: 12.0, match3Payout: 14.0 },
  { id: "p7", src: process.env.PUBLIC_URL + "/puppypics/7.jpg", match2Payout: 12.0, match3Payout: 14.0 },
  { id: "p7", src: process.env.PUBLIC_URL + "/puppypics/7.jpg", match2Payout: 12.0, match3Payout: 14.0 },
  { id: "p7", src: process.env.PUBLIC_URL + "/puppypics/7.jpg", match2Payout: 12.0, match3Payout: 14.0 },
  { id: "p7", src: process.env.PUBLIC_URL + "/puppypics/7.jpg", match2Payout: 12.0, match3Payout: 14.0 },
  { id: "p8", src: process.env.PUBLIC_URL + "/puppypics/8.jpg", match2Payout: 14.0, match3Payout: 16.0 },
  { id: "p8", src: process.env.PUBLIC_URL + "/puppypics/8.jpg", match2Payout: 14.0, match3Payout: 16.0 },
  { id: "p8", src: process.env.PUBLIC_URL + "/puppypics/8.jpg", match2Payout: 14.0, match3Payout: 16.0 },
  { id: "p8", src: process.env.PUBLIC_URL + "/puppypics/8.jpg", match2Payout: 14.0, match3Payout: 16.0 },
  { id: "p8", src: process.env.PUBLIC_URL + "/puppypics/8.jpg", match2Payout: 14.0, match3Payout: 16.0 },
  { id: "p9", src: process.env.PUBLIC_URL + "/puppypics/9.jpg", match2Payout: 16.0, match3Payout: 18.0 },
  { id: "p9", src: process.env.PUBLIC_URL + "/puppypics/9.jpg", match2Payout: 16.0, match3Payout: 18.0 },
  { id: "p9", src: process.env.PUBLIC_URL + "/puppypics/9.jpg", match2Payout: 16.0, match3Payout: 18.0 },
  { id: "p9", src: process.env.PUBLIC_URL + "/puppypics/9.jpg", match2Payout: 16.0, match3Payout: 18.0 },
  { id: "p9", src: process.env.PUBLIC_URL + "/puppypics/9.jpg", match2Payout: 16.0, match3Payout: 18.0 },

  { id: "p10", src: process.env.PUBLIC_URL + "/puppypics/10.jpg", match2Payout: 0.0, match3Payout: 30.0 },
  { id: "p10", src: process.env.PUBLIC_URL + "/puppypics/10.jpg", match2Payout: 0.0, match3Payout: 30.0 },

  { id: "p11", src: process.env.PUBLIC_URL + "/puppypics/11.jpg", match2Payout: 0.0, match3Payout: 0.0 },
  // { id: "p11", src: process.env.PUBLIC_URL + "/puppypics/11.jpg", match2Payout: 0.0, match3Payout: 0.0 },
 
]


